### ISSUE TITLE
Remove unecessary data from vector tiles

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/VectorMap#33]
Working list of data that can be removed from the vector tiles:
- [x] House numbers
- [ ] `bus`, `park`, and `school` classes in `poi` layer
   
   ```
        park:
          subclass: ['park', 'bbq']
        bus:
          subclass: ['bus_stop', 'bus_station']
        school:
          subclass: ['school', 'kindergarten']
   ```
- [x] Empty `name_*` fields in `transportation_name` layer. E.g., road 443
- [x] Remove languages other than `he`, `en`, and `de`.
